use crate::profile::{SkillFormat, ToolProfile};

fn home_dir() -> String {
    dirs_next().unwrap_or_else(|| String::from("~"))
}

fn dirs_next() -> Option<String> {
    std::env::var("HOME")
        .or_else(|_| std::env::var("USERPROFILE"))
        .ok()
}

/// Returns all 14 supported tool profiles
pub fn all_tools() -> Vec<ToolProfile> {
    let home = home_dir();
    vec![
        // === SKILL.md 互通组 ===
        ToolProfile {
            id: "codebuddy".into(),
            name: "CodeBuddy".into(),
            description: "Tencent CodeBuddy Code".into(),
            skills_dirs: vec![format!("{}/.codebuddy/skills", home)],
            rules_dirs: vec![],
            context_files: vec![],
            skill_format: SkillFormat::SkillMdYaml,
            has_rules: false,
            has_skills: true,
            rules_extension: String::new(),
            skill_filename: "SKILL.md".into(),
        },
        ToolProfile {
            id: "claude-code".into(),
            name: "Claude Code".into(),
            description: "Anthropic Claude Code".into(),
            skills_dirs: vec![format!("{}/.claude/skills", home)],
            rules_dirs: vec![format!("{}/.claude/rules", home)],
            context_files: vec!["CLAUDE.md".into()],
            skill_format: SkillFormat::SkillMdYaml,
            has_rules: true,
            has_skills: true,
            rules_extension: ".md".into(),
            skill_filename: "SKILL.md".into(),
        },
        ToolProfile {
            id: "trae".into(),
            name: "Trae".into(),
            description: "ByteDance Trae IDE".into(),
            skills_dirs: vec![
                format!("{}/.trae/skills", home),
                ".trae/skills".into(),
            ],
            rules_dirs: vec![
                format!("{}/.trae/rules", home),
                ".trae/rules".into(),
            ],
            context_files: vec!["CLAUDE.md".into()],
            skill_format: SkillFormat::SkillMdYaml,
            has_rules: true,
            has_skills: true,
            rules_extension: ".md".into(),
            skill_filename: "SKILL.md".into(),
        },
        ToolProfile {
            id: "cursor".into(),
            name: "Cursor".into(),
            description: "Anysphere Cursor IDE".into(),
            skills_dirs: vec![".cursor/skills".into()],
            rules_dirs: vec![".cursor/rules".into()],
            context_files: vec![],
            skill_format: SkillFormat::SkillMdYaml,
            has_rules: true,
            has_skills: true,
            rules_extension: ".mdc".into(),
            skill_filename: "SKILL.md".into(),
        },
        // === 单文件上下文组 ===
        ToolProfile {
            id: "codex".into(),
            name: "Codex (OpenAI)".into(),
            description: "OpenAI Codex CLI".into(),
            skills_dirs: vec![format!("{}/.codex/skills", home)],
            rules_dirs: vec![],
            context_files: vec!["AGENTS.md".into(), "CLAUDE.md".into()],
            skill_format: SkillFormat::PlainMd,
            has_rules: false,
            has_skills: true,
            rules_extension: String::new(),
            skill_filename: "skill.md".into(),
        },
        ToolProfile {
            id: "gemini-cli".into(),
            name: "Gemini CLI".into(),
            description: "Google Gemini CLI".into(),
            skills_dirs: vec![],
            rules_dirs: vec![],
            context_files: vec!["GEMINI.md".into()],
            skill_format: SkillFormat::ContextFile,
            has_rules: false,
            has_skills: false,
            rules_extension: String::new(),
            skill_filename: "GEMINI.md".into(),
        },
        ToolProfile {
            id: "copilot".into(),
            name: "GitHub Copilot".into(),
            description: "Microsoft GitHub Copilot".into(),
            skills_dirs: vec![],
            rules_dirs: vec![".github".into()],
            context_files: vec![".github/copilot-instructions.md".into()],
            skill_format: SkillFormat::ContextFile,
            has_rules: false,
            has_skills: false,
            rules_extension: String::new(),
            skill_filename: "copilot-instructions.md".into(),
        },
        ToolProfile {
            id: "aider".into(),
            name: "Aider".into(),
            description: "Aider AI Coding Assistant".into(),
            skills_dirs: vec![],
            rules_dirs: vec![],
            context_files: vec!["CONVENTIONS.md".into()],
            skill_format: SkillFormat::ContextFile,
            has_rules: false,
            has_skills: false,
            rules_extension: String::new(),
            skill_filename: "CONVENTIONS.md".into(),
        },
        // === 工具规则组 ===
        ToolProfile {
            id: "windsurf".into(),
            name: "Windsurf".into(),
            description: "Codeium Windsurf IDE".into(),
            skills_dirs: vec![],
            rules_dirs: vec![
                format!("{}/.codeium/windsurf", home),
                ".".into(),
            ],
            context_files: vec![".windsurfrules".into()],
            skill_format: SkillFormat::RulesFile,
            has_rules: true,
            has_skills: false,
            rules_extension: String::new(),
            skill_filename: ".windsurfrules".into(),
        },
        ToolProfile {
            id: "cline".into(),
            name: "Cline".into(),
            description: "Cline VS Code Extension".into(),
            skills_dirs: vec![],
            rules_dirs: vec![".cline/rules".into()],
            context_files: vec![".clinerules".into()],
            skill_format: SkillFormat::RulesFile,
            has_rules: true,
            has_skills: false,
            rules_extension: String::new(),
            skill_filename: ".clinerules".into(),
        },
        ToolProfile {
            id: "continue".into(),
            name: "Continue".into(),
            description: "Continue Dev".into(),
            skills_dirs: vec![],
            rules_dirs: vec![".continue/rules".into()],
            context_files: vec![],
            skill_format: SkillFormat::RulesFile,
            has_rules: true,
            has_skills: false,
            rules_extension: String::new(),
            skill_filename: String::new(),
        },
        ToolProfile {
            id: "amazon-q".into(),
            name: "Amazon Q".into(),
            description: "AWS Amazon Q Developer".into(),
            skills_dirs: vec![],
            rules_dirs: vec![".amazonq/rules".into()],
            context_files: vec![],
            skill_format: SkillFormat::RulesFile,
            has_rules: true,
            has_skills: false,
            rules_extension: ".md".into(),
            skill_filename: String::new(),
        },
        ToolProfile {
            id: "augment".into(),
            name: "Augment Code".into(),
            description: "Augment Code IDE".into(),
            skills_dirs: vec![],
            rules_dirs: vec![".augment/rules".into()],
            context_files: vec![],
            skill_format: SkillFormat::RulesFile,
            has_rules: true,
            has_skills: false,
            rules_extension: ".md".into(),
            skill_filename: String::new(),
        },
        ToolProfile {
            id: "codeium".into(),
            name: "Codeium".into(),
            description: "Codeium AI".into(),
            skills_dirs: vec![],
            rules_dirs: vec![format!("{}/.codeium", home)],
            context_files: vec![],
            skill_format: SkillFormat::ConfigJson,
            has_rules: true,
            has_skills: false,
            rules_extension: String::new(),
            skill_filename: String::new(),
        },
    ]
}
